destination: public
source: jekyll

title: Yogi @ Git
email: yogendra.rampuria@gmail.com
description: My Code Thought!
google_analytics: 
twitter_username: yogendra
github_username: yogendra
show_downloads: false
# theme: minima
# markdown: kramdown

plugins:
  - jekyll-mentions
  - jekyll-feed
